### ISSUE TITLE
SyntaxError when running

### ISSUE THREAD

**Issue by nuriel77** [crholliday/iota-prom-exporter#1]
Hello, I cloned the repository and followed the installation instructions.
When I run I get:
```# node app.js
/tmp/iota-prom-exporter/app.js:47
    async function getResults() {
          ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

Some details:
```
# node --version
v6.12.2
# npm --version
3.10.10
```

Installation:
```
git clone https://github.com/crholliday/iota-prom-exporter.git
...
cd iota-prom-exporter/
npm install
...
node app.js
....
(then the error)
```

**Comment by crholliday** [comment]
Nuriel, you will need to use NodeJS 8+.
