### ISSUE TITLE
iota-prom-exporter with 0mq

### ISSUE THREAD

**Issue by antonionardella** [crholliday/iota-prom-exporter#14]
Hi,

I'm trying to use the iota-prom-exporter (ipe for short) with iri and 0mq on docker

As soon as ipe starts i get the following info in the log:

zmq socket connected
Listening on: 9311
Connected to Bitfinex websocket
TypeError: Value is not a valid number: undefined
    at /exporter/node_modules/prom-client/lib/gauge.js:219:10
    at Gauge.set (/exporter/node_modules/prom-client/lib/gauge.js:85:31)
    at getResults (/exporter/app.js:72:31)
    at `<anonymous>`
    at process._tickCallback (internal/process/next_tick.js:160:7)
TypeError: Value is not a valid number: undefined
    at /exporter/node_modules/prom-client/lib/gauge.js:219:10
    at Gauge.set (/exporter/node_modules/prom-client/lib/gauge.js:85:31)
    at getResults (/exporter/app.js:72:31)
    at `<anonymous>`
    at process._tickCallback (internal/process/next_tick.js:160:7)

What am I doing wrong?

Thank you

**Comment by crholliday** [comment]
fixed on latest version
